pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      -  make build

  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: dther/golang-http
    dockerfile: Dockerfile
    tags: ${DRONE_COMMIT_SHA}
    when:
      event: [ push, tag ]

  kustomize:
    secrets: [GITHUB_TOKEN]
    image: docker:git
    commands:
      - export GT=${GITHUB_TOKEN}
      - env
      - git clone -b deploy https://dtherhtun:${GT}@github.com/dtherhtun/drone-app.git
      - cd drone-app;
      - sed -i "s+dther/golang-http:.*$*+dther/golang-http:${DRONE_COMMIT_SHA}+g" kustomize/bases/hola/deployment.yaml
      - cat kustomize/bases/hola/deployment.yaml
      - sed -i "s+dtherhtun:+dtherhtun:${GT}+g" .git/config
      - cat .git/config
      - git add .
      - git config --global user.name "drone-ci"
      - git config --global user.email ci@drone.io
      - git commit -m "Change image version to ${DRONE_COMMIT_SHA}" -a
      - git push origin deploy
