pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      -  make build

  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: dther/golang-http
    dockerfile: Dockerfile
    default_tags: true
    when:
      event: [ push, tag ]

  deploy:
    image: danielgormly/drone-plugin-kube:0.0.1
    settings:
      template: deployment.yaml # relative to repo root
      ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EWXlNekUwTlRnek5Wb1hEVE14TURZeU1URTBOVGd6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUENxClhCWE1iTHlrQ2JmdWx6L1FyS3RJNEJTYWNRMktHU3JqelVPdWVhOExaN0dEVVBJUGp6MCtjbTdneHhIMEcxSTIKZWUyZXVqRXppSklUUG9vb0dlMlBSUGFRQXExWENjTFp2dUhGaXVBR0pQVlFYdVluUkFwNkNKOTJ3cm83djI3eQpKK3EyYmNRa1MyZlJFTXZtWWFWZHk3T3JWVTc1bm1ZcTRBYkNvU3hTUEk2dnlQNkgzNml5cXdlenl0RWo0Q3huCkxrcHhnc0hIQVMzSGk3WFM1ZDVmVSt3QlFWOEkrVEVTRk5GbllaKzF0bUhpblhzMk55QUlELzJjNUNDM3RSR04Kakh6NnlzN2Y1M0xtWENvSzR1eURWcWd5Q0ZJTmlUWktBVGIrSnN5ODNUekVCZjM0L1hsTGJpNCtwWWRWN0JKdwpCb3NsSERKZjBDTXRpMGJJeThVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQcVcvc3M3MDBPTnRaaWlBV3p1UTBFVytvY2tNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFEVnY5Sk05eDltZ3lqUkc4Q3ZsN2d3cE1JOWtxNWEzN1RVeW1Qc0xNSlFKRVZjbmU1KwpmMHNtMkZkczRNVDVmSlRxakp2bkhSdGc5Tmd1VmZ0MjY0T2Q0eFZ3dDAvMHpoVm1UTk1TcmhPa003SFNLdk16Cnd4cXVvTDY1M0ZrMzJwdjg0VXBIeklHVFlHblNpNElTMlB3STM4dGN6Z0Zabk1WYzM3QWxNbUZ0T093bXJ1ZmwKclhDS2ZoT0ZlTUsyQkxFUDI1UGt3QXFxREZsclNUMUk1YW0zcG1zZ1p2aVVNTGRvUmwwdE9aZGpaYXArYmV0ZgpldlZzM2ZPbWRDaEFaK29VRURWamZCb0g4WTUwTnVHcW1ST2dneDhyeXZFTUR5NjAxUjVhTlNlVjAxS0lGZ0c2ClozcEtOL3E5VElibXFSRHJZankxT2xMOGtBQWxMODF5OFgzaAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://CD7ACE616F05FD0EDFAC13966C08B831.gr7.us-west-2.eks.amazonaws.com
      token:
        from_secret: kubernetes_token # Service account token to a service account that can manage deployments