pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      -  make build

  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: dther/golang-http
    dockerfile: Dockerfile
    tags: ${DRONE_COMMIT_SHA}
    when:
      event: [ push, tag ]

  kustomize:
    image: docker:git
    commands:
      - sed -i 's+newTag:.*$*+newTag: "${DRONE_COMMIT_SHA}"+g" kustomize/overlays/production/kustomization.yaml
      - git config --local user.email "action@github.com"
      - git config --local user.name "GitHub Action"
      - git commit -m "Change image version to ${DRONE_COMMIT_SHA}" -a
      - git push origin main
