pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      -  make build

  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: dther/golang-http
    dockerfile: Dockerfile
    tags: ${DRONE_COMMIT_SHA}
    when:
      event: [ push, tag ]

  kustomize:
    image: docker:git
    commands:
      - git fetch origin deploy
      - git checkout deploy
      - sed -i "s+dther/golang-http:.*$*+dther/golang-http:${DRONE_COMMIT_SHA}+g" kustomize/bases/hola/deployment.yaml
      - cat kustomize/bases/hola/deployment.yaml
      - git add .
      - git config --global user.name "drone-ci"
      - git config --global user.email ci@drone.io
      - git commit -m "Change image version to ${DRONE_COMMIT_SHA}" -a
  
  push:
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: deploy
      local_branch: deploy
      ssh_key:
        from_secret: ssh_key

