pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      -  make build

  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: dther/golang-http
    dockerfile: Dockerfile
    default_tags: true
    when:
      event: [ push, tag ]

  deploy:
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server:
        from_secret: kubernetes_server
      kubernetes_cert:
        from_secret: kubernetes_cert
      kubernetes_token:
        from_secret: kubernetes_token
    commands:
      - kubectl apply -f deployment.yml
