pipeline:
  build_linux_amd64:
    image: golang:1.10
    group: build
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      -  make build

  docker_golang:
    image: plugins/docker:17.12
    secrets: [ docker_username, docker_password ]
    repo: dther/golang-http
    dockerfile: Dockerfile
    default_tags: true
    when:
      event: [ push, tag ]

  deploy:
    image: danielgormly/drone-plugin-kube:0.0.2
    settings:
      template: deployment.yaml
      ca:
        from_secret: kubernetes_cert
      server:
        from_secret: kubernetes_server
      token:
        from_secret: kubernetes_token